# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.3
  - smartcontractkit/chainlink@1.8.0
compiler:
  solc:
    remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
    - '@openzeppelin_upgrade=OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.3'
    - '@chainlink=smartcontractkit/chainlink@1.8.0'

# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: False
  ganache:
    verify: False
  goerli:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}

  # could also do from_mnemonic, and you'd have to change the accounts.add to accounts.from_mnemonic
